[
			wwww.github.com/shreeshh/pattern-recognition-iiith/tree/master/SRIP/Libraries/Data/T1/images/2.gif,
			wwww.github.com/shreeshh/pattern-recognition-iiith/tree/master/SRIP/Libraries/Data/T1/images/22.gif,
			wwww.github.com/shreeshh/pattern-recognition-iiith/tree/master/SRIP/Libraries/Data/T1/images/35.gif,
			wwww.github.com/shreeshh/pattern-recognition-iiith/tree/master/SRIP/Libraries/Data/T1/images/38.gif,
			wwww.github.com/shreeshh/pattern-recognition-iiith/tree/master/SRIP/Libraries/Data/T1/images/52.gif,
			wwww.github.com/shreeshh/pattern-recognition-iiith/tree/master/SRIP/Libraries/Data/T1/images/57.gif, 
			wwww.github.com/shreeshh/pattern-recognition-iiith/tree/master/SRIP/Libraries/Data/T1/images/64.gif,
			wwww.github.com/shreeshh/pattern-recognition-iiith/tree/master/SRIP/Libraries/Data/T1/images/69.gif,
			wwww.github.com/shreeshh/pattern-recognition-iiith/tree/master/SRIP/Libraries/Data/T1/images/70.gif,
			wwww.github.com/shreeshh/pattern-recognition-iiith/tree/master/SRIP/Libraries/Data/T1/images/76.gif,
			wwww.github.com/shreeshh/pattern-recognition-iiith/tree/master/SRIP/Libraries/Data/T1/images/82.gif,
			wwww.github.com/shreeshh/pattern-recognition-iiith/tree/master/SRIP/Libraries/Data/T1/images/89.gif,
			wwww.github.com/shreeshh/pattern-recognition-iiith/tree/master/SRIP/Libraries/Data/T1/images/96.gif,
			wwww.github.com/shreeshh/pattern-recognition-iiith/tree/master/SRIP/Libraries/Data/T1/images/109.gif,
			wwww.github.com/shreeshh/pattern-recognition-iiith/tree/master/SRIP/Libraries/Data/T1/images/115.gif,
			wwww.github.com/shreeshh/pattern-recognition-iiith/tree/master/SRIP/Libraries/Data/T1/images/119.gif,
			wwww.github.com/shreeshh/pattern-recognition-iiith/tree/master/SRIP/Libraries/Data/T1/images/120.gif,
			wwww.github.com/shreeshh/pattern-recognition-iiith/tree/master/SRIP/Libraries/Data/T1/images/122.gif,
			wwww.github.com/shreeshh/pattern-recognition-iiith/tree/master/SRIP/Libraries/Data/T1/images/157.gif,
			wwww.github.com/shreeshh/pattern-recognition-iiith/tree/master/SRIP/Libraries/Data/T1/images/170.gif,
			wwww.github.com/shreeshh/pattern-recognition-iiith/tree/master/SRIP/Libraries/Data/T1/images/193.gif,
			wwww.github.com/shreeshh/pattern-recognition-iiith/tree/master/SRIP/Libraries/Data/T1/images/207.gif,
			wwww.github.com/shreeshh/pattern-recognition-iiith/tree/master/SRIP/Libraries/Data/T1/images/210.gif,
			wwww.github.com/shreeshh/pattern-recognition-iiith/tree/master/SRIP/Libraries/Data/T1/images/211.gif, 
			wwww.github.com/shreeshh/pattern-recognition-iiith/tree/master/SRIP/Libraries/Data/T1/images/217.gif,
			wwww.github.com/shreeshh/pattern-recognition-iiith/tree/master/SRIP/Libraries/Data/T1/images/4.gif,
			wwww.github.com/shreeshh/pattern-recognition-iiith/tree/master/SRIP/Libraries/Data/T1/images/7.gif,
			wwww.github.com/shreeshh/pattern-recognition-iiith/tree/master/SRIP/Libraries/Data/T1/images/9.gif,
			wwww.github.com/shreeshh/pattern-recognition-iiith/tree/master/SRIP/Libraries/Data/T1/images/15.gif,
			wwww.github.com/shreeshh/pattern-recognition-iiith/tree/master/SRIP/Libraries/Data/T1/images/24.gif,
			wwww.github.com/shreeshh/pattern-recognition-iiith/tree/master/SRIP/Libraries/Data/T1/images/25.gif,
			wwww.github.com/shreeshh/pattern-recognition-iiith/tree/master/SRIP/Libraries/Data/T1/images/41.gif,
			wwww.github.com/shreeshh/pattern-recognition-iiith/tree/master/SRIP/Libraries/Data/T1/images/60.gif,
			wwww.github.com/shreeshh/pattern-recognition-iiith/tree/master/SRIP/Libraries/Data/T1/images/68.gif,
			wwww.github.com/shreeshh/pattern-recognition-iiith/tree/master/SRIP/Libraries/Data/T1/images/71.gif,
			wwww.github.com/shreeshh/pattern-recognition-iiith/tree/master/SRIP/Libraries/Data/T1/images/73.gif,
			wwww.github.com/shreeshh/pattern-recognition-iiith/tree/master/SRIP/Libraries/Data/T1/images/78.gif,
			wwww.github.com/shreeshh/pattern-recognition-iiith/tree/master/SRIP/Libraries/Data/T1/images/79.gif,
			wwww.github.com/shreeshh/pattern-recognition-iiith/tree/master/SRIP/Libraries/Data/T1/images/100.gif,
			wwww.github.com/shreeshh/pattern-recognition-iiith/tree/master/SRIP/Libraries/Data/T1/images/103.gif,
			wwww.github.com/shreeshh/pattern-recognition-iiith/tree/master/SRIP/Libraries/Data/T1/images/105.gif,
			wwww.github.com/shreeshh/pattern-recognition-iiith/tree/master/SRIP/Libraries/Data/T1/images/106.gif, 
			wwww.github.com/shreeshh/pattern-recognition-iiith/tree/master/SRIP/Libraries/Data/T1/images/113.gif,
			wwww.github.com/shreeshh/pattern-recognition-iiith/tree/master/SRIP/Libraries/Data/T1/images/114.gif,
			wwww.github.com/shreeshh/pattern-recognition-iiith/tree/master/SRIP/Libraries/Data/T1/images/125.gif,
			wwww.github.com/shreeshh/pattern-recognition-iiith/tree/master/SRIP/Libraries/Data/T1/images/129.gif,
			wwww.github.com/shreeshh/pattern-recognition-iiith/tree/master/SRIP/Libraries/Data/T1/images/135.gif,
			wwww.github.com/shreeshh/pattern-recognition-iiith/tree/master/SRIP/Libraries/Data/T1/images/153.gif,
			wwww.github.com/shreeshh/pattern-recognition-iiith/tree/master/SRIP/Libraries/Data/T1/images/175.gif,
			wwww.github.com/shreeshh/pattern-recognition-iiith/tree/master/SRIP/Libraries/Data/T1/images/178.gif

				],







